name: Run Python Script Daily

on:
  schedule:
    # Esegui alle 8:00 e 16:00 UTC ogni giorno
    - cron: '0 8,18 * * *'
  workflow_dispatch:  # Permette l'esecuzione manuale

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version | sed 's/[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')
        wget https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.53/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set up Xvfb (Virtual display) for Selenium
      run: |
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp &  # La flag '-nolisten tcp' evita i problemi di Xauthority
        export DISPLAY=:99

    - name: Create a unique user data directory for Chrome
      run: |
        mkdir -p $HOME/chrome_user_data_$GITHUB_RUN_ID  # Usa l'ID del run per la directory unica
        echo "Using directory: $HOME/chrome_user_data_$GITHUB_RUN_ID"
    - name: Run script
      run: |
        python scraper.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        API_KEY: ${{ secrets.API_KEY }}
        INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
        INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
        OPENAIKEY: ${{ secrets.OPENAIKEY }}
        CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
        USER_DATA_DIR: $HOME/chrome_user_data_$GITHUB_RUN_ID  # Passa la directory unica di dati utente



